### PR TITLE
Use GitHub packages

### LINKED ISSUE #4: Issues about importing this project
After I got an official response from Instagram4J creator, I decided to migrate my project to use this library.
However, I have a few questions before I even write the first line of code:

1.  Why do I also need to include the `OkHttp` dependency - why isn't it included in the artifact?

2. Why do I have to download the jar myself? That's Maven and Gradle exist.
I highly recommend posting Jitpack dependencies.

### PR DESCRIPTION
**Pull request by ncovercash**
This PR does a few things:

### Add a GitHub workflow

This allows PRs/commits to automatically be checked for compilation, as well as deployment to GitHub packages whenever a new release is created.

### Use GitHub packages for deployment

This fixes #4 since we would no longer rely on Jitpack.  Instead, this adds a "Packages" section to the main repository page (as seen on [my fork](https://github.com/ncovercash/JxInsta)):
image

This can be configured to provide snapshot/tip-of-main releases, but I'm not sure what version management (if any) is here, so that can come later.  As of now, this will publish a package **on release** using the `version` in `build.gradle` (again, not sure if that should go elsewhere, but this is a starting point).

One caveat for this is that GH expects lowercase artifacts IDs, and the deployment will fail otherwise, hence the use of `jx-insta` there.

### Change the group name

Not sure what `Libraries` was, but I imagine you want this to look like `EasyInsta.JxInsta` instead, so I changed the root project name in `settings.gradle`.  Also, not sure what a number of those dependencies are, or if they were carried over from some other project or something?

### CODE REVIEW

**Comment by ErrorxCode** [comment]
I appreciate your contribution and fix for that problem. Unfortunately, packages published on **Github Packages** require **authentication** to be used by the build automation tools. Hence, it is not recommended for public libraries.

See [this](https://github.com/orgs/community/discussions/25979) discussion and this [answer](https://github.com/orgs/community/discussions/25979#discussioncomment-3249894)

_Thanks for your hard work and time, anyway :)_

**Comment by ncovercash** [comment]
Ah, I'm used to using GH packages for docker images, which does not require authentication.  It might not be a bad idea to keep the CI build step at least, though.

**Comment by ErrorxCode** [comment]
Alright! change your PR and commits to set-it only for for CI however, for distributing the library, we will use **jitpack**

**Pro tip :** You can also automate the publishing/building of the library on **jitpack** using **Github Actions**. So that on every release, the new version will be automatically build on jitpack :)

_PS : If you are interested, I can provide you with more hints and guidance on how to do that_

**Review by ErrorxCode — COMMENTED** [review]
Actually all my libraries are build in a single project with different modules. The rest `include` are the name of those modules.

You can safely remove them is it does not interfere in the build.

**Review by ErrorxCode — COMMENTED** [review]
That looks nice :)

**Comment by ErrorxCode** [comment]
Inactive for 6 months

**Pull request closed without merging**
